"""add_question_id_to_chat_messages

Revision ID: 08558639fa8a
Revises: d5f7c8b2e1a9
Create Date: 2026-07-06 11:53:13.501282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08558639fa8a'
down_revision: Union[str, Sequence[str], None] = 'd5f7c8b2e1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_messages_question_id'), 'chat_messages', ['question_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_question_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'question_id')
    # ### end Alembic commands ###
