"""Add QuestionExplanation cache table

Revision ID: 773a76f37290
Revises: f37af5091e6a
Create Date: 2026-02-26 13:37:50.692930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773a76f37290'
down_revision: Union[str, Sequence[str], None] = 'f37af5091e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('wrong_option', sa.String(length=1), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'wrong_option', name='uq_explanation_question_option')
    )
    op.create_index('ix_explanations_question_option', 'question_explanations', ['question_id', 'wrong_option'], unique=False)
    op.create_index(op.f('ix_question_explanations_question_id'), 'question_explanations', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_explanations_wrong_option'), 'question_explanations', ['wrong_option'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_explanations_wrong_option'), table_name='question_explanations')
    op.drop_index(op.f('ix_question_explanations_question_id'), table_name='question_explanations')
    op.drop_index('ix_explanations_question_option', table_name='question_explanations')
    op.drop_table('question_explanations')
    # ### end Alembic commands ###
