"""Production schema: profiles, chat, AI audit, exam_questions

Revision ID: f37af5091e6a
Revises: 1a2b3c4d5e6f
Create Date: 2026-02-26 12:31:41.033786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37af5091e6a'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('explanation', 'hint', 'chat', 'feedback', name='ai_action_type'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_logs_action', 'ai_usage_logs', ['action_type'], unique=False)
    op.create_index('ix_ai_logs_user_date', 'ai_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_action_type'), 'ai_usage_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_ai_usage_logs_user_id'), 'ai_usage_logs', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_attempt_created', 'chat_messages', ['attempt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_attempt_id'), 'chat_messages', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'question_id')
    )
    op.create_index('ix_exam_questions_exam', 'exam_questions', ['exam_id'], unique=False)
    op.create_index('ix_exam_questions_question', 'exam_questions', ['question_id'], unique=False)
    op.add_column('attempt_feedback', sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_attempt_feedback_selected_choice_id'), table_name='attempt_feedback')
    op.create_index('ix_feedback_attempt_question', 'attempt_feedback', ['attempt_id', 'question_id'], unique=False)
    op.drop_index(op.f('ix_attempts_topic_id'), table_name='attempts')
    op.add_column('attempts', sa.Column('incorrect_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('attempts', sa.Column('omitted_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_attempts_user_completed', 'attempts', ['user_id', 'completed_at'], unique=False)
    op.create_index('ix_attempts_user_status', 'attempts', ['user_id', 'status'], unique=False)
    op.add_column('exams', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('exams', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.create_index(op.f('ix_exams_is_custom'), 'exams', ['is_custom'], unique=False)
    op.drop_constraint(op.f('payments_buy_order_key'), 'payments', type_='unique')
    op.create_index('ix_payments_created', 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.add_column('questions', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.create_index('ix_questions_topic_active', 'questions', ['topic_id', 'is_active'], unique=False)
    op.create_index('ix_sessions_user_started', 'study_sessions', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_subject_exam_code', 'subjects', ['exam_id', 'code'], unique=False)
    op.create_index('ix_topic_subject_code', 'topics', ['subject_id', 'code'], unique=False)
    op.create_index(op.f('ix_user_entitlements_is_active'), 'user_entitlements', ['is_active'], unique=False)
    op.add_column('user_progress', sa.Column('total_answered', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_progress', sa.Column('total_correct', sa.Integer(), nullable=False, server_default='0'))
    op.create_index('ix_progress_user_activity', 'user_progress', ['user_id', 'last_activity_at'], unique=False)
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('academic_level', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('target_university', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('target_degree', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('target_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=False, server_default='student'))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_is_premium'), 'users', ['is_premium'], unique=False)
    op.create_index('ix_users_premium', 'users', ['is_premium'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_premium', table_name='users')
    op.drop_index(op.f('ix_users_is_premium'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'role')
    op.drop_column('users', 'target_score')
    op.drop_column('users', 'target_degree')
    op.drop_column('users', 'target_university')
    op.drop_column('users', 'academic_level')
    op.drop_column('users', 'age')
    op.drop_column('users', 'avatar_url')
    op.drop_index('ix_progress_user_activity', table_name='user_progress')
    op.drop_column('user_progress', 'total_correct')
    op.drop_column('user_progress', 'total_answered')
    op.drop_index(op.f('ix_user_entitlements_is_active'), table_name='user_entitlements')
    op.drop_index('ix_topic_subject_code', table_name='topics')
    op.drop_index('ix_subject_exam_code', table_name='subjects')
    op.drop_index('ix_sessions_user_started', table_name='study_sessions')
    op.drop_index('ix_questions_topic_active', table_name='questions')
    op.drop_column('questions', 'image_url')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index('ix_payments_created', table_name='payments')
    op.create_unique_constraint(op.f('payments_buy_order_key'), 'payments', ['buy_order'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_exams_is_custom'), table_name='exams')
    op.drop_column('exams', 'created_at')
    op.drop_column('exams', 'is_custom')
    op.drop_index('ix_attempts_user_status', table_name='attempts')
    op.drop_index('ix_attempts_user_completed', table_name='attempts')
    op.create_index(op.f('ix_attempts_topic_id'), 'attempts', ['topic_id'], unique=False)
    op.drop_column('attempts', 'omitted_count')
    op.drop_column('attempts', 'incorrect_count')
    op.drop_index('ix_feedback_attempt_question', table_name='attempt_feedback')
    op.create_index(op.f('ix_attempt_feedback_selected_choice_id'), 'attempt_feedback', ['selected_choice_id'], unique=False)
    op.drop_column('attempt_feedback', 'time_spent_seconds')
    op.drop_index('ix_exam_questions_question', table_name='exam_questions')
    op.drop_index('ix_exam_questions_exam', table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_attempt_id'), table_name='chat_messages')
    op.drop_index('ix_chat_attempt_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_ai_usage_logs_user_id'), table_name='ai_usage_logs')
    op.drop_index(op.f('ix_ai_usage_logs_action_type'), table_name='ai_usage_logs')
    op.drop_index('ix_ai_logs_user_date', table_name='ai_usage_logs')
    op.drop_index('ix_ai_logs_action', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    # ### end Alembic commands ###
