/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint
         *
         *     GET /api/v1/health/
         *     Returns: {"status": "ok"}
         */
        get: operations["health_check_api_v1_health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Registra un nuevo usuario encriptando su contraseña.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Inicia sesión validando el correo y la contraseña.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Retorna datos del usuario actual para rehidratar la sesión del frontend.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ai Feedback
         * @description Endpoint para obtener feedback generado por IA.
         *
         *     Futuro: aquí se llamará al LLM para generar explicaciones personalizadas.
         *     Hoy: retorna feedback escrito basado en reglas predefinidas.
         */
        get: operations["ai_feedback_api_v1_ai_feedback__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/exams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exams
         * @description GET /api/v1/catalog/exams/
         *
         *     Obtiene lista de exámenes disponibles.
         *
         *     Returns:
         *     [
         *         {
         *             "exam_id": 1,
         *             "code": "PAES",
         *             "title": "PAES 2024",
         *             "subjects": [...]
         *         }
         *     ]
         */
        get: operations["get_exams_api_v1_catalog_exams__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/subjects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subjects
         * @description GET /api/v1/catalog/subjects/?exam_id=1
         *
         *     Obtiene asignaturas de un examen.
         *
         *     Query params:
         *     - exam_id: ID del examen
         *
         *     Returns:
         *     [
         *         {
         *             "subject_id": 1,
         *             "subject_code": "MATH1",
         *             "name": "Matemática 1",
         *             "topics": [...]
         *         }
         *     ]
         */
        get: operations["get_subjects_api_v1_catalog_subjects__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/topics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topics
         * @description GET /api/v1/catalog/topics/?subject_id=1
         *
         *     Obtiene temas de una asignatura.
         *
         *     Query params:
         *     - subject_id: ID de la asignatura
         *
         *     Returns:
         *     [
         *         {
         *             "topic_id": 1,
         *             "topic_code": "ALGEBRA",
         *             "name": "Álgebra"
         *         }
         *     ]
         */
        get: operations["get_topics_api_v1_catalog_topics__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/next-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Question */
        get: operations["next_question_api_v1_quiz_next_question_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quiz/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_api_v1_quiz_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Stats */
        get: operations["user_stats_api_v1_users__user_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Question */
        post: operations["create_question_api_v1_questions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Questions Bulk */
        post: operations["create_questions_bulk_api_v1_questions_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recent Questions */
        get: operations["list_recent_questions_api_v1_questions_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIFeedbackOut */
        AIFeedbackOut: {
            /** Explanation */
            explanation: string;
            /** Is Correct */
            is_correct: boolean;
            /** Source */
            source: string;
            /** Correct Choice Id */
            correct_choice_id?: number | null;
            /** Correct Choice Label */
            correct_choice_label?: string | null;
        };
        /** AnswerIn */
        AnswerIn: {
            /** User Id */
            user_id?: number | null;
            /** Subject Code */
            subject_code: string;
            /** Topic Code */
            topic_code: string;
            /** Question Id */
            question_id: number;
            /** Selected Choice Id */
            selected_choice_id: number;
        };
        /** AnswerOut */
        AnswerOut: {
            /** Attempt Id */
            attempt_id: number;
            /** Feedback Id */
            feedback_id: number;
            /** Is Correct */
            is_correct: boolean;
            /** Feedback Text */
            feedback_text: string;
            /** Is Attempt Finished */
            is_attempt_finished: boolean;
            /**
             * Ai Payload
             * @default {}
             */
            ai_payload: {
                [key: string]: unknown;
            };
        };
        /** AuthTokenOut */
        AuthTokenOut: {
            /** Access Token */
            access_token: string;
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** BulkQuestionCreateIn */
        BulkQuestionCreateIn: {
            /** Questions */
            questions: components["schemas"]["QuestionCreateIn"][];
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * Atomic
             * @default false
             */
            atomic: boolean;
        };
        /** BulkQuestionCreateOut */
        BulkQuestionCreateOut: {
            /** Dry Run */
            dry_run: boolean;
            /** Atomic */
            atomic: boolean;
            /** Total */
            total: number;
            /** Created */
            created: number;
            /** Skipped */
            skipped: number;
            /**
             * Question Ids
             * @default []
             */
            question_ids: number[];
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["BulkQuestionErrorOut"][];
        };
        /** BulkQuestionErrorOut */
        BulkQuestionErrorOut: {
            /** Index */
            index: number;
            /** Error */
            error: string;
            /** Detail */
            detail?: string | null;
        };
        /** ChoiceOut */
        ChoiceOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QuestionChoiceIn */
        QuestionChoiceIn: {
            /**
             * Label
             * @enum {string}
             */
            label: "A" | "B" | "C" | "D";
            /** Text */
            text: string;
        };
        /** QuestionCreateIn */
        QuestionCreateIn: {
            /** Subject Code */
            subject_code: string;
            /** Topic Code */
            topic_code: string;
            /** Prompt */
            prompt: string;
            /** Reading Text */
            reading_text?: string | null;
            /** Explanation */
            explanation?: string | null;
            /**
             * Difficulty
             * @default 1
             */
            difficulty: number;
            /** Choices */
            choices: components["schemas"]["QuestionChoiceIn"][];
            /**
             * Correct Choice
             * @enum {string}
             */
            correct_choice: "A" | "B" | "C" | "D";
        };
        /** QuestionCreatedOut */
        QuestionCreatedOut: {
            /** Question Id */
            question_id: number;
            /** Subject Code */
            subject_code: string;
            /** Topic Code */
            topic_code: string;
            /** Prompt */
            prompt: string;
            /** Reading Text */
            reading_text?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Difficulty */
            difficulty: number;
            /** Choices */
            choices: components["schemas"]["ChoiceOut"][];
            /**
             * Correct Choice
             * @enum {string}
             */
            correct_choice: "A" | "B" | "C" | "D";
        };
        /** QuestionOut */
        QuestionOut: {
            /**
             * Kind
             * @default question
             * @constant
             */
            kind: "question";
            /** Question Id */
            question_id: number;
            /** Prompt */
            prompt: string;
            /** Topic */
            topic: string;
            /** Reading Text */
            reading_text?: string | null;
            /** Choices */
            choices: components["schemas"]["ChoiceOut"][];
        };
        /** RecentQuestionOut */
        RecentQuestionOut: {
            /** Question Id */
            question_id: number;
            /** Subject Code */
            subject_code: string;
            /** Topic Code */
            topic_code: string;
            /** Prompt */
            prompt: string;
            /** Reading Text */
            reading_text?: string | null;
            /** Difficulty */
            difficulty: number;
            /** Created At */
            created_at: string;
            /** Choices */
            choices: components["schemas"]["ChoiceOut"][];
        };
        /** TopicCompletedOut */
        TopicCompletedOut: {
            /**
             * Kind
             * @default topic_completed
             * @constant
             */
            kind: "topic_completed";
            /** Message */
            message: string;
            /** Attempt Id */
            attempt_id: number;
            /** Status */
            status: string;
            /** Total Questions */
            total_questions: number;
            /** Correct Count */
            correct_count: number;
            /** Score Percentage */
            score_percentage: number;
            /** Score Paes */
            score_paes: number;
            /** Score */
            score: number;
        };
        /** UserLoginIn */
        UserLoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** UserMeOut */
        UserMeOut: {
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** UserRegisterIn */
        UserRegisterIn: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_feedback_api_v1_ai_feedback__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIFeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exams_api_v1_catalog_exams__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_subjects_api_v1_catalog_subjects__get: {
        parameters: {
            query: {
                exam_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topics_api_v1_catalog_topics__get: {
        parameters: {
            query: {
                subject_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_question_api_v1_quiz_next_question_get: {
        parameters: {
            query?: {
                attempt_id?: number | null;
                topic_code?: string;
                subject_code?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"] | components["schemas"]["TopicCompletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_v1_quiz_answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_stats_api_v1_users__user_id__stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_v1_questions__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_questions_bulk_api_v1_questions_bulk_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkQuestionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkQuestionCreateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_questions_api_v1_questions_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentQuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
